core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('quiz.urls'))
]

quiz/urls.py
from django.urls import path
from . import views

app_name='quiz'

urlpatterns = [
    path('home', views.home, name='home'),
    path('question/<int:game_id>/', views.question, name='question'),
    path('options', views.options, name='options'),
    path('scoreboard/<int:game_id>/', views.scoreboard, name='scoreboard'),
]

quiz/models.py
'''import ranom module methods'''
from random import shuffle, randint, choice
from django.db import models


class Category(models.Model):
    """Category type of questions, first of 2 base game options"""
    name = models.CharField(max_length = 24)

    def __str__(self):
        return str(self.name)

class Pet(models.Model):
    """Player's companion, second of base game options"""
    name = models.CharField(max_length = 24)

    proudness = models.IntegerField(default=5)
    helpfulness = models.IntegerField(default=5)
    confidnece = models.IntegerField(default=5)

    knowledge = models.IntegerField(default=5)

    def __str__(self):
        return str(self.name)


    def roll_reaction_success(self, trait):
        '''If pet's trait is high, retrun succes (1)'''
        if randint(0, 10) < trait:
            return 1
        else:
            return 0

    def roll_reaction_key(self):
        '''roll dictionary key for pet reaction'''
        traits = [self.proudness, self.helpfulness, self.confidnece,]
        key = ''
        for trait in traits:
            result = self.roll_reaction_success(trait)
            key += str(result)
        return key

    def check_reaction_key(self, key, pet_answer, false_answer):
        '''Pet reaction. Check the key, get reaction and pre-rolled answer or false answer'''
        reactions = {
            '100':"You must be kidding, you should know it.",
            '110':f"Poor human, the answer is {pet_answer}.",
            '111':f"So easy. It's {pet_answer}.",
            '010':f"I have no idea what is it, maybe {pet_answer}?",
            '011':f"The answer is {pet_answer}!",
            '000':'No idea...',
            '001':f"I'm sure it is not {false_answer}.",
            '101':"I know it but i won't tell you.",

        }
        return reactions[key]

    def roll_answer(self, question):
        '''Return true answer if pet knows it or false '''
        if self.roll_reaction_success(self.knowledge):
            return question.true_answer
        else:
            return question.get_random_false_answer()


class Question(models.Model):
    '''Single question model'''
    category = models.ForeignKey(Category, on_delete= models.PROTECT)
    text = models.TextField()
    true_answer = models.CharField(max_length=64)
    false_answer1 = models.CharField(max_length=64)
    false_answer2 = models.CharField(max_length=64)
    false_answer3 = models.CharField(max_length=64)

    def get_random_false_answer(self):
        '''Return random false answer'''
        false_answers = [self.false_answer1, self.false_answer2, self.false_answer3]
        return choice(false_answers)

    def get_shuffled_answers(self):
        '''Return list of shuffled answers'''
        answers = [self.true_answer,
            self.false_answer1,
            self.false_answer2,
            self.false_answer3,]
        shuffle(answers)
        return answers

    def answer_is_true(self, answer):
        '''Check is answer true or not'''
        if answer == self.true_answer:
            return True
        else:
            return False

class Game(models.Model):
    'Model with game statistics and options'
    category = models.ForeignKey(Category, on_delete= models.PROTECT)
    pet = models.ForeignKey(Pet, on_delete= models.PROTECT)
    player_name = models.CharField(max_length = 24)
    is_finished =models.BooleanField(default=False)

    total_score = models.IntegerField(default = 0)
    current_question_index = models.IntegerField(default = 0)
    total_number_of_questions = models.IntegerField(default = 10)

    questionset = models.ManyToManyField(Question)

    def __len__(self):
        return abs(self.total_number_of_questions)

    def get_question(self):
        '''Get current question from questionset'''
        return list(self.questionset.all())[self.current_question_index]

    def start_new_game(self):
        "Create, shuffle questionset and get first question"
        questions = list(Question.objects.filter(category=self.category))
        shuffle(questions)
        questions = questions[:self.total_number_of_questions]

        for question in questions:
            self.questionset.add(question)
        self.save()

    def add_score(self):
        '''Add ten points for true answer'''
        self.total_score += 10

quiz/forms.py
from django import forms
from .models import Game


class GameForm(forms.ModelForm):
	'''Form with basic options to start game'''
	class Meta:
		model = Game
		fields = ['player_name', 'category', 'pet']
		widgets =  {
				'player_name' : forms.TextInput(attrs={'class': 'form-control'}),
				'category': forms.RadioSelect(attrs={'class': 'd-inline'}),
				'pet': forms.RadioSelect(attrs={'class': 'd-inline'}),
				}

quiz/views.py
from django.shortcuts import render, redirect
from .models import Game
from .forms import GameForm

def home(request):
    '''Render home page'''
    context = {}
    return render(request, 'quiz/home.html', context)

def question(request, game_id):
    '''Render single question page'''
    game = Game.objects.get(id=game_id)
    player_answer = request.POST.get('player_answer')
    pet = game.pet

    while not game.is_finished:
        if request.method == 'POST':
            # questions [2:]
            prev_question = game.get_question()
            if prev_question.answer_is_true(player_answer):
                game.add_score()
            game.current_question_index+=1
            game.save()
            if game.current_question_index >= len(game):
                game.is_finished = True
                game.save()
                continue
            question = game.get_question()
            answers = question.get_shuffled_answers()
            answers = [('A', answers[0]),
                    ('B', answers[1]),
                    ('C', answers[2]),
                    ('D', answers[3]),
            ]
            # pet reaction
            key = pet.roll_reaction_key()
            pet_answer = pet.roll_answer(question)
            false_answer = question.get_random_false_answer()
            pet_reaction = pet.check_reaction_key(key=key, pet_answer=pet_answer, false_answer=false_answer)

        elif request.method != 'POST':
            # first question
            if not game.questionset.all():
                # If questionset is empty roll questions
                game.start_new_game()
            question = game.get_question()
            answers = question.get_shuffled_answers()
            answers = [('A', answers[0]),
                    ('B', answers[1]),
                    ('C', answers[2]),
                    ('D', answers[3]),
            ]
            #first pet reaction
            pet_reaction = "I will try to help you but remember, it's your test."

        context ={'question':question, 'answers':answers, 'game':game, 'pet_reaction': pet_reaction}
        return render(request, 'quiz/question.html', context)
    else:
        return redirect('quiz:scoreboard', game.id)

def options(request):
    '''Render pre-game page with basic game options form'''
    if request.method != 'POST':
        form = GameForm()
        context = {'form':form}
        return render (request, 'quiz/options.html', context)
    else:
        form = GameForm(data=request.POST)
        if form.is_valid:
            game=form.save()
        return redirect ('quiz:question', game.id)


def scoreboard(request, game_id=0):
    '''Render scoreboard page'''

    context= {}
    if game_id:
        player_game = Game.objects.get(id=game_id)
        context['game']=player_game

    games = list(Game.objects.filter(is_finished=True).order_by('-total_score'))
    scoreboard_rows = 10

    while len(games) < scoreboard_rows:
        games.append(None)

    games = enumerate((games)[:scoreboard_rows])
    context['games']=games

    return render(request, 'quiz/scoreboard.html', context)

quiz/templates/quiz/base.html
{% load static %}
{% load randomimage %}

<!doctype html>
  <html lang="pl">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Quiz</title>
      <link rel="icon" href="{% static 'images/icon.PNG' %}">
      <!-- BOOTSTRAP 5 -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <!-- mycss -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <!-- googlefonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    </head>

    <nav class="d-flex justify-content-between">
      <a class="link-dark fs-1 text-decoration-none" href="{% url 'quiz:home' %}">
          <img class="nav_image " src="{% static 'images/home.PNG' %}" alt="home">
          <span class="mx-auto">HOME</span>
      </a>
      <a class="link-dark fs-1 text-decoration-none" href="{% url 'quiz:scoreboard' 0 %}">
        <span class="mx-auto mt-2">SCORES</span>
        <img class="nav_image" src="{% static 'images/cup.png' %}" alt="scoreboard">
      </a>
    </nav>

    <body>
      <div class="container rounded f-flex justify-content-center">
          {% block content %}
          {% endblock content %}
      </div>
      <img class = "body_image position-absolute bottom-0 end-0 background_image" src="{% static 'images/'%}{% random_image %}" alt="dog & cat">     
    </body>
</html>

quiz/templates/quiz/home.html
{% extends 'quiz/base.html' %}
{% load static %}
{% block content %}

<div class="row p-5 gutter-0">
    <div class="col-md-4 p-2 shadow">
        <img class ="img-fluid" src="{% static 'images/sketch.PNG' %}" alt="image">
    </div>
    <div class="container col-md-8 p-5 shadow">
      <h1 class="display-5 fw-bold ">Welcome, Human!</h1>
      <p class="fs-4 text-secondary">Glad you are here! Take a part in our quiz and check your knowledge in choosen category. Dont be afraid, we will try to help you!</p>
      <p class="float-end fst-italic fs-4">Mr. Cat &  Mr. Dog</p>
      <a class ="fs-3 p-2" href="{% url 'quiz:options' %}">
          <button class="mbtn">Play!</button>
        </a>      
    </div>
  </div>

{% endblock content %}

quiz/templates/quiz/options.html
{% extends 'quiz/base.html' %}
{% load static %}
{% block content %}

  <div class="row p-5 gutter-0">
    <div class="col-md-4 p-2 shadow text-center">

      <div class="card mb-3" style="max-width: 540px; border:none;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{% static 'images/cat.PNG' %}" class="img-fluid rounded-start pt-5" alt="cat imge">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title fw-bold fs-3">Cat</h5>
              <p class="card-text pt-3 text-start">Clever and stoic, but proud and lazy.</p>
            </div>
          </div>
        </div>
      </div>
      <div class="card mb-3" style="max-width: 540px; border:none;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{% static 'images/dog.PNG' %}" class="img-fluid rounded-start pt-5" alt="dog image">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title fw-bold fs-3">Dog</h5>
              <p class="card-text pt-3 text-start">Eager and helpful, but overconfident.</p>
            </div>
          </div>
        </div>
        <p class="pt-3 text-secondary">Be careful, pets may be wrong !</p>
      </div>      
    </div>
    <div class="container col-md-8 p-5 shadow">
      <form action="{% url 'quiz:options' %}" method="post" class = 'row'>
        {% csrf_token %}
        <div class="mb-4 col-12">
          <label for="player_name" class="form-label fs-4 fw-bold">Enter your name :</label>
          {{form.player_name}}
        </div>
        <div class="mb-4 col-6">
          <label for="player_name" class="form-label fs-4 fw-bold">Select category :</label>
          {{form.category}}
        </div>
        <div class="mb-4 col-6">
          <label for="player_name" class="form-label fs-4 fw-bold" value="">Select your pet :</label>
          {{form.pet}}
        </div>
        <div class="col-12"><button class="mbtn">Start!</button></div>
      </form> 
    </div>
  </div>

{% endblock content %}

quiz/templates/quiz/question.html
{% extends 'quiz/base.html' %}
{% load static %}
{% block content %}

	<div class="row p-5 gutter-0">
		<div class="col-md-4 p-2 shadow">
			{% if game.pet.name == "Cat" %}
			<img class ="img-fluid" src="{% static 'images/cat.PNG' %}" alt="image">
			{% endif %}
			{% if game.pet.name == "Dog" %}
			<img class ="img-fluid" src="{% static 'images/dog.PNG' %}" alt="image">
			{% endif %}
			<p class="border rounded-pill text-center p-2">{{pet_reaction}}</p>
		</div>
		<div class="container col-md-8 p-5 shadow">
		  <h1 class="fw-bold ">Question : {{game.current_question_index|add:"1"}} / {{game.total_number_of_questions}}</h1>
		  <p class="fs-4 text-secondary">{{question.text}}</p>
		  <form action="{% url 'quiz:question' game.id %}" method="post">
			{% csrf_token %}
				<div class="row">
				{% for letter, answer in answers %}
				<div class="form-check col-6">
					<input class="form-check-input" type="radio" name="player_answer" value={{answer}}>
					<label class="form-check-label" for="player_answer">
					  {{letter}}) {{answer}}
					</label>
				</div>
				{% endfor %}
				</div>
				<div class="col-12 mt-5"><button class="mbtn">Next!</button></div>
			</form>    
		</div>
	  </div>

{% endblock content %}

quiz/templates/quiz/scoreboard.html
{% extends 'quiz/base.html' %}
{% block content %}

<div class="row">
	{% if game %}
	<div class="col-5 order-md-2 d-flex flex-column align-items-center justify-content-center">
		<h1>Congratulations, {{game.player_name}} !</h1> 
		<h2 class="pb-5">You have awarded {{game.total_score}} points!</h2>
	</div>
	{% endif %}
	<div class="col-7">
		<h1 class="pt-3 fw-bold">Scoreboard:</h1>
		<table class="table table-bordered shadow" style="max-width: 800px;">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Player</th>
					<th scope="col">Pet</th>
					<th scope="col">Score</th>
				</tr>
			</thead>
			<tbody>
				{% for nr, game in games %}
					{% if game %}
						<tr>
							<th scope="row">{{nr|add:'1'}}</th>
							<td>{{game.player_name}}</td>
							<td>{{game.pet}}</td>
							<td>{{game.total_score}}</td>
						</tr>
					{% else %}
						<tr>
							<th scope="row">{{nr|add:'1'}}</th>
							<td>...</td>
							<td>...</td>
							<td>...</td>
						</tr>
					{% endif %}
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% endblock content %}